### PR TITLE
Add job for merging OMERO guides

### PR DESCRIPTION
**Pull request by sbesson**
Implemented a few weeks back to integrate all PRs opened against the various guides and push them to integration branches

### CODE REVIEW

**Comment by joshmoore** [comment]
In general, a huge :+1: for having jobs that to cover all the newer sets of repositories. I do wonder though if a meta-merge job wouldn't spare us some of the difficulties. (This is timely for me since I'm wondering whether or not to go the supermodule root with the various `*-zarr-*` repositories.)

**Comment by joshmoore** [comment]
Hmm.... good points. Perhaps this is just too large to tackle at the moment (which is probably why it _isn't_ tackled). There's also the question of whether or not GH actions could help with some of this, though I think that might still require putting the coupling logic after the merge/push logic. Happy to keep the conversation going, but we shouldn't block this PR with it.

**Comment by sbesson** [comment]
Understood, proposing to merge this (and #170), tag and deploy the new jobs in `latest-ci` in a first instance.
Should I turn this conversation into an issue ?

**Comment by sbesson** [comment]
Tagged as `0.15.5` and merged the tag into merge-ci/latest-ci

**Pull request merged**
