### PR TITLE
install node 10

### PR DESCRIPTION
**Pull request by jburel**
Install node 10
The change has been made to merge-ci directly manually
I had to remove the previous version of node in order to install it

### CODE REVIEW

**Comment by joshmoore** [comment]
WFM. Next chance to test will likely be spinning up of an integration devspace.

cc: @sbesson

**Comment by sbesson** [comment]
:+1: from my side too. I have two other potential devspace PRs:

- one backporting some of the diff between `0.15.0` and the state of the systems following the Python 3 work - see https://github.com/ome/devspace/pull/162#issuecomment-595067243
- one updating the BIOFORMATS docs job - see https://github.com/ome/bio-formats-documentation/pull/151

Proposing to open all of this, spin up an ephemerous devspace for validation and merge?

**Comment by jburel** [comment]
sounds like a plan

**Comment by jburel** [comment]
Closing this PR
The version has now been bump to node 12

**Pull request closed without merging**
